<?php
/**
 * config.php — BankEase application settings
 *
 * This file only defines constants. It contains no logic and produces
 * no output, so it is safe to include from any page or API endpoint.
 *
 * Change the DB_* values below if your MySQL setup is different
 * (the values shown are the XAMPP defaults).
 */

/* ------------------------------------------------------------------
 * Database connection
 * ------------------------------------------------------------------ */
define('DB_HOST',    '127.0.0.1');   // MySQL server address
define('DB_PORT',    3306);          // MySQL port (XAMPP default)
define('DB_NAME',    'bankease');    // Database created by the DDL script
define('DB_USER',    'root');        // XAMPP default user
define('DB_PASS',    '');            // XAMPP default password is empty
define('DB_CHARSET', 'utf8mb4');     // Matches the DDL (supports Bangla text)

/* ------------------------------------------------------------------
 * Application settings
 * ------------------------------------------------------------------ */
define('APP_NAME',     'BankEase');                       // Shown in the page header
define('APP_SUBTITLE', 'Banking Database Management System');
define('APP_TIMEZONE', 'Asia/Dhaka');                     // Used for all timestamps
define('CURRENCY',     'BDT');                            // Matches accounts.currency default
define('RECORDS_PER_PAGE', 10);                 // rows per page in list views
define('DATE_FORMAT',      'Y-m-d');            // PHP date() format for DATE columns
define('DATETIME_FORMAT',  'Y-m-d H:i:s');      // PHP date() format for DATETIME columns
/*
 * Debug mode.
 * true  = show PHP errors on screen (useful while developing / in viva)
 * false = hide them
 */
define('APP_DEBUG', true);

/* ------------------------------------------------------------------
 * "Performed by" user
 * ------------------------------------------------------------------
 * The project has no login system, but the schema requires every row in
 * transactions.performed_by_user_id (NOT NULL) to point at users.user_id,
 * and loans.approved_by_user_id also points at users.user_id.
 *
 * So every transaction and loan approval created by this application is
 * recorded against this single, fixed user. user_id = 1 is the first row
 * inserted by BankEase_system_management_DML.sql.
 * Change this number if you want a different user to appear in the records.
 */
define('DEFAULT_USER_ID', 1);

/* ------------------------------------------------------------------
 * Apply the settings that PHP itself needs
 * ------------------------------------------------------------------ */

// All date() / NOW()-style values generated by PHP use this timezone.
date_default_timezone_set(APP_TIMEZONE);

// Show or hide PHP errors according to APP_DEBUG.
if (APP_DEBUG) {
    ini_set('display_errors', '1');
    error_reporting(E_ALL);
} else {
    ini_set('display_errors', '0');
    error_reporting(0);
}